title: Byte Me, Maybe?
email: iskyd@proton.me
description: >-
  As Batman once said, 'Why so serious?'
baseurl: "/blog"
url: "https://iskyd.github.io"
icon: /blog/assets/images/favicon.ico
github_username:  iskyd

markdown: kramdown

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"

hide_search: true