title: Hello
email: iskyd@proton.me
description: 
baseurl: "/blog"
url: "https://iskyd.github.io"
icon: /blog/assets/images/favicon.ico
github_username:  iskyd

# markdown: kramdown

# plugins:
#   - jekyll-paginate
# 
# paginate: 5
# paginate_path: "/page/:num/"

theme: no-style-please

hide_search: true
